- hosts: webserver 
  become: yes
  vars:
    docker_compose_version: "1.27.4"
    ansible_user: ubuntu
  tasks:

    # - name: Update apt cache
    #   apt: update_cache=yes


- hosts: monitoring 
  become: yes
  vars:
    docker_compose_version: "1.27.4"
    ansible_user: ubuntu
  
  roles:

    - prometheus
      

