# - hosts: webserver 
#   become: yes
#   vars:
#     docker_compose_version: "1.27.4"
#     ansible_user: ubuntu
#   tasks:

#     # - name: Update apt cache
#     #   apt: update_cache=yes

- hosts: apachewebserver 
  become: yes
  vars:
    docker_compose_version: "1.27.4"
    ansible_user: ubuntu
  
  roles:
    - apache_exporter

- hosts: webserver 
  become: yes
  vars:
    docker_compose_version: "1.27.4"
    ansible_user: ubuntu
  
  roles:
    - nginx_exporter    


- hosts: monitoring 
  become: yes
  vars:
    docker_compose_version: "1.27.4"
    ansible_user: ubuntu
  
  roles:
    - alert-manager
    - prometheus
 
    
      

