---
# tasks file for apache_exporter
- name: Create prometheus system group
  ansible.builtin.group:
    name: prometheus
    system: true
    state: present

- name: Create prometheus system user
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
    

- name: Get apache exporter binary
  block:

    - name: Download apache exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/Lusitaniae/apache_exporter/releases/download/v1.0.1/apache_exporter-1.0.1.linux-amd64.tar.gz"
        dest: "/tmp/apache_exporter-1.0.1.linux-amd64.tar.gz"
        mode: 0644
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      # run_once: true # <-- this cannot be set due to multi-arch support
      delegate_to: localhost
      check_mode: false

    - name: Unpack apache exporter binaries
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/apache_exporter-1.0.1.linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/apache_exporter-1.0.1.linux-amd64"
      delegate_to: localhost
      check_mode: false

    - name: Copy apache exporter binaries to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/apache_exporter-1.0.1.linux-amd64/apache_exporter"
        dest: "/usr/local/bin"
        mode: 0755
        owner: root
        group: root

    - name: Create systemd service unit
      ansible.builtin.copy:
        src: apache_exporter.service
        dest: /etc/systemd/system/apache_exporter.service
        force: true
        mode: 0755
        owner: root
        group: root
        mode: 0644
      notify:
        - restart apache_exporter    
      